@baseUrl = http://localhost:3333

### Create endpoint
# @name createEndpoint
POST {{baseUrl}}/endpoints
Content-Type: application/json

{
    "title": "Categoria criada",
    "method": "GET",
    "statusCode": 204
}

###
@endpointId = {{createEndpoint.response.body.data.id}}

### Update endpoint
# @name updateEndpoint
PATCH {{baseUrl}}/endpoints/{{endpointId}}
Content-Type: application/json

{
    "title": "Categoria atualizada",
    "method": "GET",
    "statusCode": 200
}


### List endpoints summary
GET {{baseUrl}}/endpoints/summary

### Find endpoint by id
GET {{baseUrl}}/endpoints/{{endpointId}}

### Delete endpoint
DELETE {{baseUrl}}/endpoints/{{endpointId}}


### Login google
POST {{baseUrl}}/auth/google/login
Content-Type: application/json

{
    "googleToken": "google-token"
}
