### STEP 1 ###
FROM node:24-slim as builder

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build

CMD [ "tail", "-f", "/dev/null"]

### STEP 2 ###
FROM node:24-slim as production

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

RUN npm prune --omit=dev

EXPOSE 3333

CMD [ "npm", "run", "start:prod"]